import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/analytics/analytics_service.dart';
import '../../core/config/environment.dart';
import '../../core/observability/crash_hooks.dart';
import '../../core/observability/crash_reporter.dart';
import '../../core/services/notification_service.dart';
import '../../firebase_options.dart';
import '../../shared/providers/analytics_providers.dart';
import '../../shared/providers/crash_providers.dart';
import '../../shared/providers/notification_providers.dart';

/// Builds the notification service the app starts with.
///
/// A parameter rather than a hard-coded constructor call so the failure path
/// below can be exercised. Whether startup survives a service that throws is a
/// promise this file makes, and a promise nothing can test is one nobody finds
/// out has been broken until a device breaks it.
typedef NotificationServiceFactory = NotificationService Function();

/// Initialises the Firebase client.
///
/// A parameter for the same reason as [NotificationServiceFactory], and one
/// more: under `flutter test` there is no platform channel, so the real call
/// throws before any test gets to run.
typedef FirebaseInitializer = Future<void> Function();

/// Builds the analytics service the app starts with.
///
/// A parameter for the same reason as the two above: the real one reads
/// `FirebaseAnalytics.instance`, which needs a platform channel no test has.
typedef AnalyticsServiceFactory = AnalyticsService Function();

/// Builds the crash reporter the app starts with.
///
/// A parameter for the same reason as the others: the real one reads
/// `FirebaseCrashlytics.instance`.
typedef CrashReporterFactory = CrashReporter Function();

/// Application bootstrap for foundation initialization.
///
/// `lib/firebase_options.dart` and the platform config files are generated by
/// the FlutterFire CLI for the `hitup-691be` project (HIT-009). Do not edit
/// them by hand; regenerate them with `flutterfire configure`.
class AppBootstrap {
  const AppBootstrap._();

  /// Prepares everything that must exist before the first frame, and returns
  /// the provider overrides the app should start with.
  ///
  /// Services whose setup is asynchronous are created and initialised here,
  /// then handed to Riverpod as an override. A provider body cannot await, so
  /// letting the provider build these itself would hand callers an instance
  /// that has not finished starting up.
  ///
  /// [initializeFirebase] and [createNotificationService] exist for tests.
  /// `main` calls this with no arguments and gets the real ones.
  static Future<List<Override>> init({
    FirebaseInitializer initializeFirebase = _initializeFirebase,
    NotificationServiceFactory createNotificationService =
        LocalNotificationService.new,
    AnalyticsServiceFactory createAnalyticsService = _createAnalyticsService,
    bool collectAnalytics = !kDebugMode,
    CrashReporterFactory createCrashReporter = _createCrashReporter,
    bool reportCrashes = !kDebugMode,
  }) async {
    WidgetsFlutterBinding.ensureInitialized();

    // Environment is local/dev until a formal env strategy is wired (HIT-009+).
    assert(() {
      // ignore: avoid_print
      print('HitUp bootstrap — environment: ${Environment.current.name}');
      return true;
    }());

    // First, and not guarded. Auth, progress and sync all sit on Firebase, so
    // nothing after this line is worth starting without it.
    //
    // This is the opposite of the notification service below, on purpose.
    // Notification setup fails because of the device, and reminders are
    // optional. Firebase.initializeApp reads config compiled into the app and
    // does not reach the network; when it throws, the build is broken, and
    // catching that here would ship a broken build that opens normally.
    await initializeFirebase();

    final NotificationService notifications = await _initNotifications(
      createNotificationService,
    );

    final AnalyticsService analytics = await _initAnalytics(
      createAnalyticsService,
      collect: collectAnalytics,
    );

    final CrashReporter crashes = await _initCrashReporting(
      createCrashReporter,
      report: reportCrashes,
    );

    return <Override>[
      notificationServiceProvider.overrideWithValue(notifications),
      analyticsServiceProvider.overrideWithValue(analytics),
      crashReporterProvider.overrideWithValue(crashes),
    ];
  }

  /// The real analytics service, over the Firebase instance.
  static AnalyticsService _createAnalyticsService() =>
      FirebaseAnalyticsService(FirebaseAnalytics.instance);

  /// The real crash reporter, over the Firebase instance.
  static CrashReporter _createCrashReporter() =>
      FirebaseCrashReporter(FirebaseCrashlytics.instance);

  /// Creates the crash reporter, sets collection, and wires the error hooks.
  ///
  /// The hooks are installed whatever [report] says. They send to the reporter,
  /// and the reporter is what decides whether anything leaves the device, so
  /// installing them in a debug build costs nothing and keeps the path the
  /// same in both builds rather than untested in one of them (HIT-065).
  static Future<CrashReporter> _initCrashReporting(
    CrashReporterFactory create, {
    required bool report,
  }) async {
    final CrashReporter reporter = create();

    try {
      await reporter.setCollectionEnabled(report);
    } on Object catch (error, stackTrace) {
      debugPrint('HIT-065: crash reporting setup failed. Cause: $error');
      debugPrintStack(stackTrace: stackTrace);
    }

    CrashHooks.install(reporter);
    return reporter;
  }

  /// Creates the analytics service and sets collection for this build.
  ///
  /// Collection is off in debug builds, so a developer running the app does
  /// not add taps to the product's numbers (HIT-063). Failure is not fatal for
  /// the same reason as notifications, only more so: analytics is a side
  /// channel, and no part of the app depends on it. When it fails the service
  /// is still returned, so call sites need no null check.
  static Future<AnalyticsService> _initAnalytics(
    AnalyticsServiceFactory create, {
    required bool collect,
  }) async {
    final AnalyticsService service = create();

    try {
      await service.setCollectionEnabled(collect);
    } on Object catch (error, stackTrace) {
      debugPrint('HIT-063: analytics setup failed. Cause: $error');
      debugPrintStack(stackTrace: stackTrace);
    }

    return service;
  }

  /// Initialises Firebase with the options generated for this project.
  static Future<void> _initializeFirebase() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  /// Creates and initialises the notification service (HIT-057).
  ///
  /// Failure here is deliberately not fatal. Reminders are one optional
  /// feature; a device that cannot set them up, or a platform channel that is
  /// unavailable, is not a reason to refuse to open the app. The service is
  /// still returned, so the reminder settings screen can report the real state
  /// through [NotificationService.areNotificationsEnabled] rather than the app
  /// pretending reminders work.
  ///
  /// The service instance is returned even when [NotificationService.init]
  /// threw. Returning null instead would move the decision to every caller,
  /// and the reminder screen would have to ask "do I have a service" before it
  /// could ask "do reminders work", which are not the same question.
  static Future<NotificationService> _initNotifications(
    NotificationServiceFactory create,
  ) async {
    final NotificationService service = create();

    try {
      await service.init();
    } on Object catch (error, stackTrace) {
      debugPrint('HIT-057: notification setup failed. Cause: $error');
      debugPrintStack(stackTrace: stackTrace);
    }

    return service;
  }
}
